site_name: agents-monitor-people Documentation
site_description: Documentation for agents-monitor-people
docs_dir: mkdocs_src
site_dir: docs
theme:
  name: material
  palette:
  - scheme: default
    primary: indigo
    accent: indigo
  features:
  - navigation.expand
nav:
- Home: index.md
- API Reference:
  - Cli.Cli: api/cli.cli.md
  - Main: api/main.md
  - Parsers.Openstates People Parser: api/parsers.openstates_people_parser.md
plugins:
- search
markdown_extensions:
- toc
- codehilite
- admonition
